name: Package Release
on:
  # Manual trigger from Github Actions tab.
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version:"
        required: true

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Prepare zip directory
        run: |
          mkdir "$GITHUB_WORKSPACE/WideQuestLogIds"
          cp "$GITHUB_WORKSPACE/LICENSE" "$GITHUB_WORKSPACE/WideQuestLogIds/LICENSE"
          cp "$GITHUB_WORKSPACE/WideQuestLogIds.lua" "$GITHUB_WORKSPACE/WideQuestLogIds/WideQuestLogIds.lua"

      # Runs a single command using the runners shell
      - name: Package classic.
        run: echo "WideQuestLogIds-v${{ github.event.inputs.releaseVersion }}-classic.zip"
      #    cp "$GITHUB_WORKSPACE/WideQuestLogIds-classic.toc" "$GITHUB_WORKSPACE/WideQuestLogIds/WideQuestLogIds.toc"
      #    zip -r "$GITHUB_WORKSPACE/WideQuestLogIds-classic.zip" "$GITHUB_WORKSPACE/WideQuestLogIds"

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
