name: Package Release
on:
  # Manual trigger from Github Actions tab.
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version:"
        required: true

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REL_VER: v${{ github.event.inputs.releaseVersion }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Prepare zip directory
        run: |
          mkdir WideQuestLogIds
          cp "${GITHUB_WORKSPACE}/LICENSE" WideQuestLogIds/LICENSE
          cp "${GITHUB_WORKSPACE}/WideQuestLogIds.lua" WideQuestLogIds/WideQuestLogIds.lua

      - name: Package classic
        run: |
          cp -f "${GITHUB_WORKSPACE}/WideQuestLogIds-classic.toc" WideQuestLogIds/WideQuestLogIds.toc
          zip -r "WideQuestLogIds-${REL_VER}-classic.zip" WideQuestLogIds

      - name: Package bcc
        run: |
          cp -f "${GITHUB_WORKSPACE}/WideQuestLogIds-bcc.toc" WideQuestLogIds/WideQuestLogIds.toc
          zip -r "WideQuestLogIds-${REL_VER}-bcc.zip" WideQuestLogIds
          
      - name: Package wrath
        run: |
          cp -f "${GITHUB_WORKSPACE}/WideQuestLogIds-wrath.toc" WideQuestLogIds/WideQuestLogIds.toc
          zip -r "WideQuestLogIds-${REL_VER}-wrath.zip" WideQuestLogIds

      - name: Create release draft
        run: gh release create $REL_VER --draft --title $REL_VER ./*.zip
