name: Package Release
on:
  # Manual trigger from Github Actions tab.
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version:"
        required: true

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Prepare zip directory
        run: |
          mkdir "$GITHUB_WORKSPACE/WideQuestLogIds"
          cp "$GITHUB_WORKSPACE/LICENSE" "$GITHUB_WORKSPACE/WideQuestLogIds/LICENSE"
          cp "$GITHUB_WORKSPACE/WideQuestLogIds.lua" "$GITHUB_WORKSPACE/WideQuestLogIds/WideQuestLogIds.lua"

      - name: Package classic
        run: |
          cp -f "$GITHUB_WORKSPACE/WideQuestLogIds-classic.toc" "$GITHUB_WORKSPACE/WideQuestLogIds/WideQuestLogIds.toc"
          zip -r "$GITHUB_WORKSPACE/WideQuestLogIds-v${{ github.event.inputs.releaseVersion }}-classic.zip" "$GITHUB_WORKSPACE/WideQuestLogIds"

      - name: Package bcc
        run: |
          cp -f "$GITHUB_WORKSPACE/WideQuestLogIds-bcc.toc" "$GITHUB_WORKSPACE/WideQuestLogIds/WideQuestLogIds.toc"
          zip -r "$GITHUB_WORKSPACE/WideQuestLogIds-v${{ github.event.inputs.releaseVersion }}-bcc.zip" "$GITHUB_WORKSPACE/WideQuestLogIds"
          
      - name: Package wrath
        run: |
          cp -f "$GITHUB_WORKSPACE/WideQuestLogIds-wrath.toc" "$GITHUB_WORKSPACE/WideQuestLogIds/WideQuestLogIds.toc"
          zip -r "$GITHUB_WORKSPACE/WideQuestLogIds-v${{ github.event.inputs.releaseVersion }}-wrath.zip" "$GITHUB_WORKSPACE/WideQuestLogIds"

      - name: Create release draft
        run: |
          gh release create "v${{ github.event.inputs.releaseVersion }}" --draft
          gh release upload "v${{ github.event.inputs.releaseVersion }}" "$GITHUB_WORKSPACE/WideQuestLogIds-v${{ github.event.inputs.releaseVersion }}-classic.zip"
          gh release upload "v${{ github.event.inputs.releaseVersion }}" "$GITHUB_WORKSPACE/WideQuestLogIds-v${{ github.event.inputs.releaseVersion }}-bcc.zip"
          gh release upload "v${{ github.event.inputs.releaseVersion }}" "$GITHUB_WORKSPACE/WideQuestLogIds-v${{ github.event.inputs.releaseVersion }}-wrath.zip"
